# Spring
spring:
  # Database
  datasource:
    url: jdbc:h2:mem:default;Mode=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  # Database
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /manage/h2-console
      settings:
        trace: false
        web-allow-others: false
server:
  port: 9003